"""Plan generator for Jira tickets."""
from datetime import datetime
from typing import Dict, List, Tuple, Optional
import os
from config import Config


class PlanGenerator:
    """Generates implementation plans from Jira ticket information."""
    
    def __init__(self, plans_dir: str = None):
        self.plans_dir = plans_dir or os.path.join(os.path.dirname(__file__), "plans")
        os.makedirs(self.plans_dir, exist_ok=True)
    
    def analyze_ticket(self, ticket: Dict) -> Tuple[bool, List[str]]:
        """
        Analyze a ticket to determine if clarification is needed.
        Returns (needs_clarification, questions_list)
        """
        questions = []
        
        summary = ticket.get("summary", "")
        description = ticket.get("description", "")
        summary_lower = summary.lower()
        
        # Check if summary contains a clear action verb - if so, trust it
        action_verbs = [
            "upgrade", "fix", "implement", "add", "remove", "update",
            "create", "refactor", "migrate", "replace", "delete", "rename",
            "move", "convert", "enable", "disable", "integrate", "deploy",
            "configure", "setup", "test", "review", "optimize", "enhance",
            "extend", "document", "cleanup", "restructure", "port"
        ]
        
        summary_is_clear = any(verb in summary_lower for verb in action_verbs)
        
        # If the summary is clear and actionable, don't ask unnecessary questions
        if summary_is_clear:
            return False, []
        
        # Only ask if BOTH summary and description are vague
        if not description or len(description.strip()) < 20:
            if not summary or len(summary.strip()) < 15:
                questions.append("The ticket is vague. Can you provide more context about what needs to be done?")
        
        # Check if scope is genuinely unclear (more than 3 components without clear focus)
        components = ticket.get("components", [])
        if len(components) > 3:
            questions.append(f"This ticket involves many components ({', '.join(components)}). Which is the primary focus?")
        
        needs_clarification = len(questions) > 0
        return needs_clarification, questions
    
    def generate_plan(self, ticket: Dict, clarifications: Optional[Dict[str, str]] = None) -> str:
        """Generate a detailed implementation plan for the ticket."""
        ticket_key = ticket.get("key", "UNKNOWN")
        summary = ticket.get("summary", "No summary")
        description = ticket.get("description", "No description provided")
        status = ticket.get("status", "Unknown")
        priority = ticket.get("priority", "Normal")
        labels = ticket.get("labels", [])
        components = ticket.get("components", [])
        
        # Estimate complexity based on various factors
        complexity = self._estimate_complexity(ticket)
        
        plan = f"""# Implementation Plan: {ticket_key}

**Generated:** {datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}
from config import Config

**Ticket:** [{ticket_key}]({Config.JIRA_BASE_URL}/browse/{ticket_key})
**Priority:** {priority}
**Status:** {status}
**Estimated Complexity:** {complexity}

---

## Summary
{summary}

## Description
{description}

## Labels
{', '.join(labels) if labels else 'None'}

## Components
{', '.join(components) if components else 'None'}

---

## Implementation Steps

"""
        
        # Add steps based on ticket analysis
        steps = self._generate_steps(ticket)
        for i, step in enumerate(steps, 1):
            plan += f"{i}. {step}\n"
        
        # Add clarifications if provided
        if clarifications:
            plan += "\n---\n\n## Clarifications Provided\n\n"
            for question, answer in clarifications.items():
                plan += f"**Q:** {question}\n**A:** {answer}\n\n"
        
        # Add questions/considerations
        plan += """---

## Questions & Considerations

"""
        considerations = self._generate_considerations(ticket)
        if considerations:
            for consideration in considerations:
                plan += f"- {consideration}\n"
        else:
            plan += "- None identified at this time\n"
        
        plan += """
---

## Definition of Done

- [ ] Code implemented and tested locally
- [ ] Code review completed
- [ ] Deployed to test environment
- [ ] QA verified
- [ ] Deployed to production
- [ ] Ticket resolved in Jira

---

*This plan was auto-generated by Jira Agent. Update as needed.*
"""
        
        return plan
    
    def _generate_steps(self, ticket: Dict) -> List[str]:
        """Generate implementation steps based on ticket type."""
        steps = []
        summary_lower = ticket.get("summary", "").lower()
        description_lower = ticket.get("description", "").lower()
        labels = [l.lower() for l in ticket.get("labels", [])]
        
        # Backend/API work
        if any(word in summary_lower for word in ["api", "endpoint", "backend", "service"]):
            steps.extend([
                "Analyze current codebase and identify affected components",
                "Design API contract/data model changes",
                "Implement core logic with unit tests",
                "Add/update API endpoints",
                "Test with Postman or similar tool",
                "Update documentation"
            ])
        
        # Frontend/UI work
        elif any(word in summary_lower for word in ["ui", "frontend", "page", "component", "button"]):
            steps.extend([
                "Review design mockups/requirements",
                "Create or update UI components",
                "Wire up to backend (if needed)",
                "Test across browsers/devices",
                "Get design review approval"
            ])
        
        # Bug fix
        elif "bug" in labels or "fix" in summary_lower or "error" in description_lower:
            steps.extend([
                "Reproduce the issue locally",
                "Identify root cause",
                "Implement fix with regression test",
                "Verify fix resolves the issue",
                "Check for similar issues elsewhere"
            ])
        
        # Default generic steps
        else:
            steps.extend([
                "Analyze requirements and existing code",
                "Design solution approach",
                "Implement core functionality",
                "Add tests for new code",
                "Review and test thoroughly",
                "Document changes"
            ])
        
        return steps
    
    def _generate_considerations(self, ticket: Dict) -> List[str]:
        """Generate considerations/warnings based on ticket."""
        considerations = []
        
        priority = ticket.get("priority", "")
        if priority in ["High", "Highest", "Critical"]:
            considerations.append("⚠️ High priority ticket - coordinate with team for quick turnaround")
        
        components = ticket.get("components", [])
        if len(components) > 1:
            considerations.append(f"🔍 Multiple components involved ({', '.join(components)}) - verify scope with stakeholders")
        
        labels = ticket.get("labels", [])
        if "security" in [l.lower() for l in labels]:
            considerations.append("🔒 Security-related ticket - ensure proper review before deployment")
        
        return considerations
    
    def _estimate_complexity(self, ticket: Dict) -> str:
        """Estimate ticket complexity."""
        score = 0
        
        # Description length as proxy for detail
        desc_len = len(ticket.get("description", ""))
        if desc_len < 50:
            score += 1  # Brief = might be simple or might be vague
        elif desc_len < 200:
            score += 2
        else:
            score += 3  # Detailed = likely complex
        
        # Number of components
        score += len(ticket.get("components", []))
        
        # Labels
        score += len(ticket.get("labels", []))
        
        # Priority
        priority = ticket.get("priority", "")
        if priority in ["Highest", "Critical"]:
            score += 2
        elif priority == "High":
            score += 1
        
        if score <= 3:
            return "Low 🟢"
        elif score <= 6:
            return "Medium 🟡"
        else:
            return "High 🔴"
    
    def save_plan(self, ticket_key: str, plan: str) -> str:
        """Save plan to file and return path."""
        filename = f"{ticket_key}_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.md"
        filepath = os.path.join(self.plans_dir, filename)
        
        with open(filepath, "w") as f:
            f.write(plan)
        
        return filepath
